### PR TITLE
Added expanding menu to FloatingActionButton

### PR DESCRIPTION
**Pull request by rahuliyer95**
Added expanding menu

#80
#103

Sample
=======

### CODE REVIEW

**Comment by rahuliyer95** [comment]
bump!! any issues please tell

**Comment by Nivl** [comment]
Nice job, maybe you should update the README too, to let people know how it works.

I hope it get merged soon!

**Comment by LeopoldPodmolik** [comment]
I think, that will be good add auto hide menus when is FAB binding to listview ... 

public void onScrollUp() {
	    if (isMenuShowing) { triggerMenu(90); } // Add to hide menus

**Comment by LeopoldPodmolik** [comment]
I try it on API 10 and I dont know if is problem with combination ListView and SwipeRefreshLayout but cant click on menus

**Comment by orrc** [comment]
It's probably worth noting that this change only works if the FAB's parent is a `FrameLayout`, which won't be the case for everybody.

**Comment by makovkastar** [comment]
Thanks a lot for your contribution but decided to keep this library simple and focused (without floation action menus but only the FAB itself).

**Pull request merged**
